server:
  port: 8091

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/web_lab_7
    username: shut_uper
    password: 371222